/*
*  This code was generated by Inca X
*
*  For more information please contact
*  support@incax.com
*  www.incax.com
*
*/

package com.incax.example;

import net.jini.admin.Administrable;

import java.io.Serializable;

public class DbServiceProxy
  implements DbService, Administrable, Serializable {

  private RemoteDbService _impl;

  DbServiceProxy
    (RemoteDbService serviceImpl) {
    _impl = serviceImpl;
  }


  public Object getAdmin() {
    return _impl;
  }

  //service methods
  public SQLResult executeQuery(java.lang.String sql) throws java.rmi.RemoteException {
    return _impl.executeQuery(sql);
  }

  public com.incax.example.SQLResult execute(com.incax.example.SQLRequest request) throws java.rmi.RemoteException {
    return _impl.execute(request);
  }


  public Object[] getPreparedStatementKeys() throws java.rmi.RemoteException {
    return _impl.getPreparedStatementKeys();
  }

  public int getNumParameters(Object perparedStatementKey) throws java.rmi.RemoteException {
    return _impl.getNumParameters(perparedStatementKey);
  }

}
