/*
*  This source code was generated by Inca X
*
*  For more information please contact
*  support@incax.com
*  www.incax.com
*
*/
package com.incax.example;

import java.rmi.RemoteException;

public interface DbService {
  //execute a pass thru SQL statement
  SQLResult executeQuery(String sql) throws RemoteException;

  //execute a prepared statement
  SQLResult execute(SQLRequest request) throws RemoteException;

  //returns an array of prepared statements
  //used for testing the example Service UI
  Object[] getPreparedStatementKeys() throws RemoteException;

  //returns the number of parameters expected for the preparedStatement
  //used for testing the example Service UI
  int getNumParameters(Object perparedStatementKey) throws RemoteException;
}
