/*
*  This code was generated by Inca X
*
*  For more information please contact
*  support@incax.com
*  www.incax.com
*
*/

package com.incax.example;

import java.rmi.Remote;

public interface RemoteDbService
  extends DbService, /*JoinAdmin, DestroyAdmin, Administrable,*/ Remote {

}
